# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10db0275224abfc7de4e51ad66bd66c1e38e1d9f404de043b07770b26ceca8b76684c9cb0a6ef6121247da59d09775c5a3b924d9924ccaf1d5105ca257a18a67

test:
  secret_key_base: 609f2d1aa1c55854bf6250745afea3301f016e12c1b106fec8aeb64bda973c3d9ab45a2476287e92ca1a97e2e64b66efb5c6d4b96bb400afc0a7fec937665cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
